server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metric
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: changeit
    username: changeit
    password: changeit
