version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./grafana/grafana_config.ini:/etc/grafana/config.ini
      - ./grafana/grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
